var canvas = document.getElementById('myCanvas');
var clearBtn = document.getElementById('clearBtn')

var context = canvas.getContext("2d");
var isDrawing = false;

// Event listener for mouse down event
canvas.addEventListener("mousedown", startDrawing);

// Event listener for mouse move event
canvas.addEventListener("mousemove", draw);

// Event listener for mouse up and mouse leave events

canvas.addEventListener("mouseleave", stopDrawing);
canvas.addEventListener("mouseup", ()=>{
    stopDrawing();
    data = context.getImageData(0, 0, 20, 20).data;
    console.log(data);
});



  

clearBtn.addEventListener("click",()=>{
    context.clearRect(0, 0, canvas.width, canvas.height);
})

function startDrawing(e) {
    isDrawing = true;
    var x = e.clientX - canvas.offsetLeft;
    var y = e.clientY - canvas.offsetTop;
    context.lineWidth = 10;
    context.beginPath();
    context.moveTo(x, y);
}

function draw(e) {
    if (!isDrawing) return;
    var x = e.clientX - canvas.offsetLeft;
    var y = e.clientY - canvas.offsetTop;
    context.lineTo(x, y);
    context.stroke();
}

function stopDrawing() {
    isDrawing = false;
}

//Code generated by chatgpt :)